export enum Role {
  SUPERADMIN = 'SUPERADMIN',
  TEAM_MAIN_OFFICE = 'TEAM_MAIN_OFFICE',
  MANAGER_MAIN_OFFICE = 'MANAGER_MAIN_OFFICE',
  FINANCE_MAIN_OFFICE = 'FINANCE_MAIN_OFFICE',
  FINANCE_MANAGER_MAIN_OFFICE = 'FINANCE_MANAGER_MAIN_OFFICE',
}

export function isManagerRole(role: Role): boolean {
  return role === Role.MANAGER_MAIN_OFFICE || role === Role.FINANCE_MANAGER_MAIN_OFFICE;
}